CREATE DATABASE IF NOT EXISTS limon_studios CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE limon_studios;
CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL DEFAULT '', email VARCHAR(254) NOT NULL, password_hash VARCHAR(255) NULL, google_id VARCHAR(191) NULL UNIQUE, phone VARCHAR(30) NULL, role ENUM('USER','ADMIN') NOT NULL DEFAULT 'USER', email_verified BOOLEAN NOT NULL DEFAULT FALSE, verification_code_hash VARCHAR(255) NULL, verification_expires_at DATETIME NULL, verification_attempts INT NOT NULL DEFAULT 0, reset_code_hash VARCHAR(255) NULL, reset_expires_at DATETIME NULL, blocked BOOLEAN NOT NULL DEFAULT FALSE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_users_email (email)
);
CREATE TABLE IF NOT EXISTS services (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(180) NOT NULL, description TEXT NOT NULL, category VARCHAR(80) NOT NULL, base_price INT UNSIGNED NOT NULL, image_url TEXT NULL, features JSON NULL, active BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE KEY uq_service_name(name), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS orders (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, public_id VARCHAR(32) NOT NULL UNIQUE, user_id BIGINT UNSIGNED NOT NULL, service_id BIGINT UNSIGNED NULL, item_name VARCHAR(180) NOT NULL, details JSON NULL, status ENUM('PENDING_PAYMENT','PAYMENT_REVIEW','PAID','IN_DEVELOPMENT','REVIEW','CORRECTIONS','DELIVERED','COMPLETED','CANCELLED') NOT NULL DEFAULT 'PENDING_PAYMENT', payment_status ENUM('PENDING','REVIEW','PAID','REJECTED','REFUNDED') NOT NULL DEFAULT 'PENDING', payment_method ENUM('FLOW','TRANSFER') NOT NULL, total INT UNSIGNED NOT NULL, estimated_days SMALLINT UNSIGNED NOT NULL DEFAULT 7, estimated_delivery_at DATETIME NULL, progress TINYINT UNSIGNED NOT NULL DEFAULT 0, transfer_receipt_url TEXT NULL, admin_notes TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_orders_user FOREIGN KEY(user_id) REFERENCES users(id), CONSTRAINT fk_orders_service FOREIGN KEY(service_id) REFERENCES services(id)
);
CREATE TABLE IF NOT EXISTS payments (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL, provider VARCHAR(40) NOT NULL, transaction_id VARCHAR(191) NULL, amount INT UNSIGNED NOT NULL, status ENUM('PENDING','PAID','FAILED','REVIEW','REFUNDED') NOT NULL DEFAULT 'PENDING', provider_response JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX idx_payment_tx(transaction_id), CONSTRAINT fk_payments_order FOREIGN KEY(order_id) REFERENCES orders(id)
);
CREATE TABLE IF NOT EXISTS custom_requests (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, service_type VARCHAR(80) NOT NULL, description TEXT NOT NULL, budget INT UNSIGNED NULL, status ENUM('NEW','QUOTED','ACCEPTED','REJECTED') NOT NULL DEFAULT 'NEW', admin_notes TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_custom_user FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS projects (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, order_id BIGINT UNSIGNED NOT NULL UNIQUE, status VARCHAR(50) NOT NULL DEFAULT 'Pedido recibido', progress TINYINT UNSIGNED NOT NULL DEFAULT 0, estimated_days SMALLINT UNSIGNED NOT NULL DEFAULT 7, estimated_delivery_at DATETIME NULL, notes TEXT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_project_order FOREIGN KEY(order_id) REFERENCES orders(id)
);
CREATE TABLE IF NOT EXISTS tickets (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, subject VARCHAR(180) NOT NULL, status ENUM('OPEN','IN_PROGRESS','CLOSED') NOT NULL DEFAULT 'OPEN', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, CONSTRAINT fk_ticket_user FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS ticket_messages (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, ticket_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NOT NULL, message TEXT NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, CONSTRAINT fk_message_ticket FOREIGN KEY(ticket_id) REFERENCES tickets(id), CONSTRAINT fk_message_user FOREIGN KEY(user_id) REFERENCES users(id)
);
CREATE TABLE IF NOT EXISTS site_settings (
 setting_key VARCHAR(100) PRIMARY KEY, setting_value TEXT NOT NULL, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS security_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, event_type VARCHAR(100) NOT NULL, ip_address VARCHAR(45) NULL, metadata JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, INDEX idx_security_created(created_at)
);
INSERT INTO services(name,description,category,base_price,features,active) VALUES
('Sitio Web Básico','Landing page responsive y formulario de contacto','web',60000,'["Landing page","Diseño responsive","WhatsApp","SEO básico"]',TRUE),
('Sitio Web Profesional','Sitio multipágina con funcionalidades ampliadas','web',100000,'["Varias páginas","Panel administrativo básico","Base de datos","Sistema de usuarios"]',TRUE),
('Sitio Web Premium','Proyecto personalizado con integraciones','web',150000,'["Diseño personalizado","Panel cliente","Panel admin","Integraciones"]',TRUE),
('Bot de Discord Básico','Bot de Discord con comandos esenciales','discord',30000,'["Moderación básica","Bienvenida","Comandos administrativos"]',TRUE)
ON DUPLICATE KEY UPDATE name=VALUES(name);
